openapi: 3.0.0
info:
  title: User Feedback API
  version: 1.0.0
  description: API documentation for the User Feedback application
tags:
  - name: Feedback
    description: Operations related to user feedback
paths:
  /api/feedback:
    post:
      tags:
        - Feedback
      summary: Create a new feedback
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                feedback:
                  type: string
                  example: "Great product!"
                product_id:
                  type: integer
                  example: 1
                user_id:
                  type: integer
                  example: 1
      responses:
        '201':
          description: Feedback created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Feedback'
              examples:
                feedback:
                  value:
                    id: 1
                    feedback: "Great product!"
                    product_id: 1
                    user_id: 1
        '500':
          description: Internal server error
    get:
      tags:
        - Feedback
      summary: Get all feedback
      responses:
        '200':
          description: A list of feedback
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Feedback'
              examples:
                feedbackList:
                  value:
                    - id: 1
                      feedback: "Great product!"
                      product_id: 1
                      user_id: 1
                      product:
                        id: 2
                        name: "Product B"
                        description: "Description for Product B"

                    - id: 2
                      feedback: "Good quality!"
                      product_id: 2
                      user_id: 2
                      product:
                        id: 2
                        name: "Product B"
                        description: "Description for Product B"
                    - id: 3
                      feedback: "Loved it!"
                      product_id: 3
                      user_id: 3
                      product:
                        id: 2
                        name: "Product B"
                        description: "Description for Product B"
        '500':
          description: Internal server error
  /api/feedback/{id}:
    get:
      tags:
        - Feedback
      summary: Get feedback by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Feedback found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Feedback'
              examples:
                feedback:
                  value:
                    id: 1
                    feedback: "Great product!"
                    product_id: 1
                    user_id: 1
        '404':
          description: Feedback not found
        '500':
          description: Internal server error
    put:
      tags:
        - Feedback
      summary: Update feedback by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                feedback:
                  type: string
                  example: "Updated feedback"
                product_id:
                  type: integer
                  example: 1
                user_id:
                  type: integer
                  example: 1
      responses:
        '200':
          description: Feedback updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Feedback'
              examples:
                feedback:
                  value:
                    id: 1
                    feedback: "Updated feedback"
                    product_id: 1
                    user_id: 1
        '403':
          description: Not allowed to update user
        '404':
          description: Feedback not found
        '500':
          description: Internal server error
    delete:
      tags:
        - Feedback
      summary: Delete feedback by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '204':
          description: Feedback deleted successfully
        '404':
          description: Feedback not found
        '500':
          description: Internal server error
components:
  schemas:
    Feedback:
      type: object
      properties:
        id:
          type: integer
          example: 1
        feedback:
          type: string
          example: "Great product!"
        product_id:
          type: integer
          example: 1
        user_id:
          type: integer
          example: 1